# Provider configuration for Trial API Orchestrator
providers:
  - id: cerebras
    name: Cerebras Inference API
    priority: 10
    base_url: "https://api.cerebras.ai"
    chat_completions_path: "/v1/chat/completions"
    availability:
      cooldown_seconds: 300
    credentials:
      type: sqlite
      key_ref: cerebras_api_key
    models:
      default: "cerebras-gpt-4o-mini"
